name: Update Subscription
on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点
  workflow_dispatch:

jobs:
  generate-subscription:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate subscription
      run: python generate_ss.py

    - name: Commit and push changes
      env:
        GH_ACTOR: ${{ github.actor }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY: ${{ github.repository }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add subscription.txt
        git commit -m "Auto-update subscription"
        git push "https://$GH_ACTOR:$GH_TOKEN@github.com/$REPOSITORY.git" HEAD:main
