name: Update Subscription
on:
  schedule:
    - cron: '0 0 * * *'  # 注意使用单引号包裹
  workflow_dispatch:      # 允许手动触发

jobs:
  generate-subscription:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 写入权限必须声明

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # 关键参数
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate subscription
      run: python generate_ss.py

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用自动生成的 Token
      run: |                                  # 多行命令使用管道符
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add subscription.txt
        git commit -m "Auto-update subscription"
        git push "https://${{ github.actor }}:$GH_TOKEN@github.com/${{ github.repository }}.git" HEAD:main
