name: Update Subscription  # 工作流名称
on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点运行（北京时间 8 点）
  workflow_dispatch:  # 允许手动触发

jobs:
  generate-subscription:
    runs-on: ubuntu-latest  # 使用 GitHub 的 Linux 虚拟机
    steps:
    - name: Checkout code  # 拉取仓库代码
      uses: actions/checkout@v4

    - name: Set up Python  # 安装 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies  # 安装依赖
      run: pip install -r requirements.txt

    - name: Generate subscription  # 运行脚本生成订阅文件
      run: python generate_ss.py

    - name: Commit and push changes  # 提交更新到仓库
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add subscription.txt
        git commit -m "Auto-update subscription"
        git push
